Issue #95: Update `add` command in User Guide
AY2122S2-CS2103-F11-2/tp pull request #161
Opened 2022-03-25 17:18 UTC by domlimm

This PR consists of the following changes:
- Update add command usage
- Remove tags related notes

Closes #95.

2022-03-25 18:00 UTC, charmainehly requested changes
Just a quick point on the format of `studentId`!

2022-03-26 06:05 UTC, domlimm commented on docs/UserGuide.md
>     * **`delete A0123456H`** : Deletes the TA with ID A0213456H from the system.
Hey, I think it has yet to be updated.

2022-03-26 06:39 UTC, lzan98 commented on docs/UserGuide.md
>     * **`delete A0123456H`** : Deletes the TA with ID A0213456H from the system.
@domlimm oops I think that was my part from weeks ago, I'll change it in another PR! Sorry I didn't approve at first cause I thought you were making a change until I realised it was about `delete` (which is my part 😅)

2022-03-26 06:41 UTC, lzan98 approved these changes
LGTM! Good reminder for me to update my sections in the UG too 😆

2022-03-26 06:45 UTC, charmainehly approved these changes
Approved!! LGTM! We'll KIV the format of `studentId`!

2022-03-26 06:49 UTC, merged